/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Spam.Model;
using Cloudmersive.APIClient.NET.Spam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Spam.Test.Model
{
    /// <summary>
    ///  Class for testing SpamDetectionAdvancedFormField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpamDetectionAdvancedFormFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionAdvancedFormField
        //private SpamDetectionAdvancedFormField instance;

        public SpamDetectionAdvancedFormFieldTests()
        {
            // TODO uncomment below to create an instance of SpamDetectionAdvancedFormField
            //instance = new SpamDetectionAdvancedFormField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionAdvancedFormField
        /// </summary>
        [Fact]
        public void SpamDetectionAdvancedFormFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpamDetectionAdvancedFormField
            //Assert.IsType<SpamDetectionAdvancedFormField>(instance);
        }

        /// <summary>
        /// Test the property 'FieldTitle'
        /// </summary>
        [Fact]
        public void FieldTitleTest()
        {
            // TODO unit test for the property 'FieldTitle'
        }

        /// <summary>
        /// Test the property 'FieldValue'
        /// </summary>
        [Fact]
        public void FieldValueTest()
        {
            // TODO unit test for the property 'FieldValue'
        }
    }
}
