/* 
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Spam.Api;
using Cloudmersive.APIClient.NET.Spam.Model;
using Cloudmersive.APIClient.NET.Spam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Spam.Test
{
    /// <summary>
    ///  Class for testing SpamDetectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SpamDetectionRequestTests
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionRequest
        //private SpamDetectionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpamDetectionRequest
            //instance = new SpamDetectionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpamDetectionRequest
        /// </summary>
        [Test]
        public void SpamDetectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SpamDetectionRequest
            //Assert.IsInstanceOfType<SpamDetectionRequest> (instance, "variable 'instance' is a SpamDetectionRequest");
        }


        /// <summary>
        /// Test the property 'InputString'
        /// </summary>
        [Test]
        public void InputStringTest()
        {
            // TODO unit test for the property 'InputString'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Test]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

    }

}
