/*
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Spam.Model;
using Cloudmersive.APIClient.NET.Spam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Spam.Test.Model
{
    /// <summary>
    ///  Class for testing SpamDetectionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpamDetectionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionResponse
        //private SpamDetectionResponse instance;

        public SpamDetectionResponseTests()
        {
            // TODO uncomment below to create an instance of SpamDetectionResponse
            //instance = new SpamDetectionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionResponse
        /// </summary>
        [Fact]
        public void SpamDetectionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpamDetectionResponse
            //Assert.IsType<SpamDetectionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
    }
}
