/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Spam.Model;
using Cloudmersive.APIClient.NET.Spam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Spam.Test.Model
{
    /// <summary>
    ///  Class for testing SpamDetectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpamDetectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionRequest
        //private SpamDetectionRequest instance;

        public SpamDetectionRequestTests()
        {
            // TODO uncomment below to create an instance of SpamDetectionRequest
            //instance = new SpamDetectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionRequest
        /// </summary>
        [Fact]
        public void SpamDetectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpamDetectionRequest
            //Assert.IsType<SpamDetectionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputString'
        /// </summary>
        [Fact]
        public void InputStringTest()
        {
            // TODO unit test for the property 'InputString'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
    }
}
