/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Spam.Model;
using Cloudmersive.APIClient.NET.Spam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Spam.Test.Model
{
    /// <summary>
    ///  Class for testing SpamDetectionAdvancedFormSubmissionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpamDetectionAdvancedFormSubmissionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionAdvancedFormSubmissionRequest
        //private SpamDetectionAdvancedFormSubmissionRequest instance;

        public SpamDetectionAdvancedFormSubmissionRequestTests()
        {
            // TODO uncomment below to create an instance of SpamDetectionAdvancedFormSubmissionRequest
            //instance = new SpamDetectionAdvancedFormSubmissionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionAdvancedFormSubmissionRequest
        /// </summary>
        [Fact]
        public void SpamDetectionAdvancedFormSubmissionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpamDetectionAdvancedFormSubmissionRequest
            //Assert.IsType<SpamDetectionAdvancedFormSubmissionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputFormFields'
        /// </summary>
        [Fact]
        public void InputFormFieldsTest()
        {
            // TODO unit test for the property 'InputFormFields'
        }

        /// <summary>
        /// Test the property 'AllowUnsolicitedSales'
        /// </summary>
        [Fact]
        public void AllowUnsolicitedSalesTest()
        {
            // TODO unit test for the property 'AllowUnsolicitedSales'
        }

        /// <summary>
        /// Test the property 'AllowPromotionalContent'
        /// </summary>
        [Fact]
        public void AllowPromotionalContentTest()
        {
            // TODO unit test for the property 'AllowPromotionalContent'
        }

        /// <summary>
        /// Test the property 'AllowPhishing'
        /// </summary>
        [Fact]
        public void AllowPhishingTest()
        {
            // TODO unit test for the property 'AllowPhishing'
        }
    }
}
