/*
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Spam.Model;
using Cloudmersive.APIClient.NET.Spam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Spam.Test.Model
{
    /// <summary>
    ///  Class for testing SpamDetectionAdvancedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpamDetectionAdvancedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionAdvancedResponse
        //private SpamDetectionAdvancedResponse instance;

        public SpamDetectionAdvancedResponseTests()
        {
            // TODO uncomment below to create an instance of SpamDetectionAdvancedResponse
            //instance = new SpamDetectionAdvancedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionAdvancedResponse
        /// </summary>
        [Fact]
        public void SpamDetectionAdvancedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpamDetectionAdvancedResponse
            //Assert.IsType<SpamDetectionAdvancedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'ContainsSpam'
        /// </summary>
        [Fact]
        public void ContainsSpamTest()
        {
            // TODO unit test for the property 'ContainsSpam'
        }

        /// <summary>
        /// Test the property 'ContainsUnsolicitedSales'
        /// </summary>
        [Fact]
        public void ContainsUnsolicitedSalesTest()
        {
            // TODO unit test for the property 'ContainsUnsolicitedSales'
        }

        /// <summary>
        /// Test the property 'ContainsPromotionalContent'
        /// </summary>
        [Fact]
        public void ContainsPromotionalContentTest()
        {
            // TODO unit test for the property 'ContainsPromotionalContent'
        }

        /// <summary>
        /// Test the property 'ContainsPhishingAttempt'
        /// </summary>
        [Fact]
        public void ContainsPhishingAttemptTest()
        {
            // TODO unit test for the property 'ContainsPhishingAttempt'
        }
    }
}
