/* 
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Spam.Api;
using Cloudmersive.APIClient.NET.Spam.Model;
using Cloudmersive.APIClient.NET.Spam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Spam.Test
{
    /// <summary>
    ///  Class for testing SpamDetectionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SpamDetectionResponseTests
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionResponse
        //private SpamDetectionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SpamDetectionResponse
            //instance = new SpamDetectionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpamDetectionResponse
        /// </summary>
        [Test]
        public void SpamDetectionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SpamDetectionResponse
            //Assert.IsInstanceOfType<SpamDetectionResponse> (instance, "variable 'instance' is a SpamDetectionResponse");
        }


        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Test]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

    }

}
