/*
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.Spam.Model;
using Cloudmersive.APIClient.NET.Spam.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.Spam.Test.Model
{
    /// <summary>
    ///  Class for testing SpamDetectionAdvancedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpamDetectionAdvancedRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpamDetectionAdvancedRequest
        //private SpamDetectionAdvancedRequest instance;

        public SpamDetectionAdvancedRequestTests()
        {
            // TODO uncomment below to create an instance of SpamDetectionAdvancedRequest
            //instance = new SpamDetectionAdvancedRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionAdvancedRequest
        /// </summary>
        [Fact]
        public void SpamDetectionAdvancedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpamDetectionAdvancedRequest
            //Assert.IsType<SpamDetectionAdvancedRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputString'
        /// </summary>
        [Fact]
        public void InputStringTest()
        {
            // TODO unit test for the property 'InputString'
        }
    }
}
