/*
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Spam.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Spam.Model
{
    /// <summary>
    /// Result of detecting spam using AI
    /// </summary>
    [DataContract(Name = "SpamDetectionAdvancedResponse")]
    public partial class SpamDetectionAdvancedResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionAdvancedResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">True if the result is not spam (clean), and false otherwise.</param>
        /// <param name="containsSpam">True if the input text contains spam, false otherwise.</param>
        /// <param name="containsUnsolicitedSales">True if the input text contains unsolicited sales, false otherwise.</param>
        /// <param name="containsPromotionalContent">True if the input text contains promotional content, false otherwise.</param>
        /// <param name="containsPhishingAttempt">True if the input text contains a phishing attempt, false otherwise.</param>
        public SpamDetectionAdvancedResponse(bool cleanResult = default(bool), bool containsSpam = default(bool), bool containsUnsolicitedSales = default(bool), bool containsPromotionalContent = default(bool), bool containsPhishingAttempt = default(bool))
        {
            this.CleanResult = cleanResult;
            this.ContainsSpam = containsSpam;
            this.ContainsUnsolicitedSales = containsUnsolicitedSales;
            this.ContainsPromotionalContent = containsPromotionalContent;
            this.ContainsPhishingAttempt = containsPhishingAttempt;
        }

        /// <summary>
        /// True if the result is not spam (clean), and false otherwise
        /// </summary>
        /// <value>True if the result is not spam (clean), and false otherwise</value>
        [DataMember(Name = "CleanResult", EmitDefaultValue = true)]
        public bool CleanResult { get; set; }

        /// <summary>
        /// True if the input text contains spam, false otherwise
        /// </summary>
        /// <value>True if the input text contains spam, false otherwise</value>
        [DataMember(Name = "ContainsSpam", EmitDefaultValue = true)]
        public bool ContainsSpam { get; set; }

        /// <summary>
        /// True if the input text contains unsolicited sales, false otherwise
        /// </summary>
        /// <value>True if the input text contains unsolicited sales, false otherwise</value>
        [DataMember(Name = "ContainsUnsolicitedSales", EmitDefaultValue = true)]
        public bool ContainsUnsolicitedSales { get; set; }

        /// <summary>
        /// True if the input text contains promotional content, false otherwise
        /// </summary>
        /// <value>True if the input text contains promotional content, false otherwise</value>
        [DataMember(Name = "ContainsPromotionalContent", EmitDefaultValue = true)]
        public bool ContainsPromotionalContent { get; set; }

        /// <summary>
        /// True if the input text contains a phishing attempt, false otherwise
        /// </summary>
        /// <value>True if the input text contains a phishing attempt, false otherwise</value>
        [DataMember(Name = "ContainsPhishingAttempt", EmitDefaultValue = true)]
        public bool ContainsPhishingAttempt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpamDetectionAdvancedResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ContainsSpam: ").Append(ContainsSpam).Append("\n");
            sb.Append("  ContainsUnsolicitedSales: ").Append(ContainsUnsolicitedSales).Append("\n");
            sb.Append("  ContainsPromotionalContent: ").Append(ContainsPromotionalContent).Append("\n");
            sb.Append("  ContainsPhishingAttempt: ").Append(ContainsPhishingAttempt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
