/* 
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloudmersive.APIClient.NET.Spam.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NET.Spam.Model
{
    /// <summary>
    /// Result of detecting spam using AI
    /// </summary>
    [DataContract]
    public partial class SpamDetectionAdvancedResponse : Dictionary<String, >,  IEquatable<SpamDetectionAdvancedResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionAdvancedResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">True if the result is not spam (clean), and false otherwise.</param>
        public SpamDetectionAdvancedResponse(bool? cleanResult = default(bool?)) : base()
        {
            this.CleanResult = cleanResult;
        }
        
        /// <summary>
        /// True if the result is not spam (clean), and false otherwise
        /// </summary>
        /// <value>True if the result is not spam (clean), and false otherwise</value>
        [DataMember(Name="CleanResult", EmitDefaultValue=false)]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpamDetectionAdvancedResponse {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpamDetectionAdvancedResponse);
        }

        /// <summary>
        /// Returns true if SpamDetectionAdvancedResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SpamDetectionAdvancedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpamDetectionAdvancedResponse input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.CleanResult == input.CleanResult ||
                    (this.CleanResult != null &&
                    this.CleanResult.Equals(input.CleanResult))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.CleanResult != null)
                    hashCode = hashCode * 59 + this.CleanResult.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
