/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Cloudmersive.APIClient.NET.Spam.Client;
using Cloudmersive.APIClient.NET.Spam.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.Spam.Model;

namespace Cloudmersive.APIClient.NET.Spam.Test.Api
{
    /// <summary>
    ///  Class for testing SpamDetectionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SpamDetectionApiTests : IDisposable
    {
        private SpamDetectionApi instance;

        public SpamDetectionApiTests()
        {
            instance = new SpamDetectionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpamDetectionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SpamDetectionApi
            //Assert.IsType<SpamDetectionApi>(instance);
        }

        /// <summary>
        /// Test SpamDetectTextStringAdvancedPost
        /// </summary>
        [Fact]
        public void SpamDetectTextStringAdvancedPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SpamDetectionAdvancedRequest body = null;
            //var response = instance.SpamDetectTextStringAdvancedPost(body);
            //Assert.IsType<SpamDetectionAdvancedResponse>(response);
        }

        /// <summary>
        /// Test SpamDetectTextStringPost
        /// </summary>
        [Fact]
        public void SpamDetectTextStringPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SpamDetectionRequest body = null;
            //var response = instance.SpamDetectTextStringPost(body);
            //Assert.IsType<SpamDetectionResponse>(response);
        }
    }
}
