/* 
 * spamapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.Spam.Client;
using Cloudmersive.APIClient.NET.Spam.Api;
using Cloudmersive.APIClient.NET.Spam.Model;

namespace Cloudmersive.APIClient.NET.Spam.Test
{
    /// <summary>
    ///  Class for testing SpamDetectionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SpamDetectionApiTests
    {
        private SpamDetectionApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SpamDetectionApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SpamDetectionApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SpamDetectionApi
            //Assert.IsInstanceOfType(typeof(SpamDetectionApi), instance, "instance is a SpamDetectionApi");
        }

        
        /// <summary>
        /// Test SpamDetectTextStringAdvancedPost
        /// </summary>
        [Test]
        public void SpamDetectTextStringAdvancedPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SpamDetectionAdvancedRequest body = null;
            //var response = instance.SpamDetectTextStringAdvancedPost(body);
            //Assert.IsInstanceOf<SpamDetectionAdvancedResponse> (response, "response is SpamDetectionAdvancedResponse");
        }
        
        /// <summary>
        /// Test SpamDetectTextStringPost
        /// </summary>
        [Test]
        public void SpamDetectTextStringPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SpamDetectionRequest body = null;
            //var response = instance.SpamDetectTextStringPost(body);
            //Assert.IsInstanceOf<SpamDetectionResponse> (response, "response is SpamDetectionResponse");
        }
        
    }

}
